name: generate animation

on:
  schedule:
    - cron: "0 22 * * *" # everyday at 10pm
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # generates a snake game from a github user <github_user_name> contributions graph, output a svg animation at <svg_out_path>
      - name: generate
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            files/github-contribution-grid-snake.svg
            files/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
